# Generated by Django 5.1.7 on 2025-03-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantemodelo',
            options={'ordering': ['-fecha_Creado']},
        ),
        migrations.RenameField(
            model_name='estudiantemodelo',
            old_name='created_at',
            new_name='fecha_Creado',
        ),
    ]
