# Generated by Django 5.1.7 on 2025-03-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_alter_estudiantemodelo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantemodelo',
            old_name='fecha_actulizado',
            new_name='fecha_actualizado',
        ),
    ]
